swagger: "2.0"
info:
  description: "Docs for LioKor Mail API"
  version: "1.0.0"
  title: "LioKor Mail"
  contact:
    email: "korolion31@yandex.ru"
basePath: "/"
tags:
- name: "user"
  description: "User operations"
paths:
  /user/auth:
    post:
      tags:
      - "user"
      summary: "Authenticates user and sets session cookie"
      description: ""
      operationId: "authUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "authData"
        description: "User auth data"
        required: true
        schema:
          $ref: "#/definitions/authData"
      responses:
        "200":
          description: "Successful authentication"
        "400":
          description: "Invalid data in request"
        "403":
          description: "Invalid login or password"
  /user/session:
    delete:
      tags:
      - "user"
      summary: "Removes user's session from db"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Not authenticated"
  /user:
    get:
      tags:
      - "user"
      summary: "Returns authenticated user data"
      responses:
        "200":
          description: "successful operation"
        "401":
          description: "Not authenticated"
    post:
      tags:
      - "user"
      summary: "Creates new user"
      description: ""
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid user data provided"
        "409":
          description: "Username already taken"
  /user/{username}:
    # get:
      # tags:
      # - "user"
      # summary: "Get user by username"
      # operationId: "getUserByName"
      # produces:
      # - "application/json"
      # parameters:
      # - name: "username"
        # in: "path"
        # required: true
        # type: "string"
      # responses:
        # "200":
          # description: "successful operation"
          # schema:
            # $ref: "#/definitions/User"
        # "404":
          # description: "User not found"
    put:
      tags:
      - "user"
      summary: "Update user by username"
      description: "Must be authenticated as {username}"
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "username that needs to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
            description: "User updated successfully"
        "400":
          description: "Invalid user data provided"
        "401":
          description: "Access denied"
        "404":
          description: "User not found"
  /user/{username}/password:
    put:
      tags:
      - "user"
      summary: "Changes password of a user specified by username"
      description: "Must be authenticated as {username}"
      operationId: "updateUserPassword"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "name that need to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Updated user object"
        required: true
        schema:
          $ref: "#/definitions/passwordChange"
      responses:
        "200":
          description: "Password changed successfully"
        "400":
          description: "Invalid password data provided"
        "401":
          description: "Access denied"
        "404":
          description: "User not found"
  /user/{username}/avatar:
    put:
      tags:
      - "user"
      summary: "Changes avatar of a user specified by username"
      description: "Must be authenticated as {username}"
      operationId: "updateUserAvatar"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "path"
        description: "username of user whose avatar needs to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "new avatar as data url"
        required: true
        schema:
          $ref: "#/definitions/avatarChange"
      responses:
        "200":
          description: "Avatar changed successfully"
        "400":
          description: "Invalid data provided"
        "401":
          description: "Access denied"
        "404":
          description: "User not found"
  /image:
    post:
      tags:
      - "user"
      summary: "Uploads and saves image in dataURL format and returns url"
      description: "Must be authenticated as {username}"
      operationId: "uploadImage"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "new avatar as data url"
        required: true
        schema:
          $ref: "#/definitions/imageUpload"
      responses:
        "200":
          description: "Image uploaded"
        "400":
          description: "Invalid data provided"
        "401":
          description: "Access denied"
  /email/dialogue:
      post:
        tags:
        - "email"
        operationId: "createDialogue"
        parameters:
        - in: "body"
          name: "body"
          description: "New dialogue data"
          required: true
          schema:
            $ref: "#/definitions/createDialogue"
        responses:
          "200":
            description: "Dialogue created"
          "401":
            description: "Not authorized"
          "404":
            description: "Dialogue already exists"
      delete:
        tags:
        - "email"
        summary: "Removes dialogue with all messages"
        description: "Must be authenticated"
        operationId: "deleteDialogue"
        parameters:
        - in: "body"
          name: "body"
          description: "dialogue id to delete"
          required: true
          schema:
            $ref: "#/definitions/deleteFolder"
        responses:
          "200":
            description: "Dialogue was deleted"
          "400":
            description: "Invalid data provided"
          "401":
            description: "Not authenticated"
  /email/dialogues:
      get:
        tags:
        - "email"
        summary: "Returns dialogues of an authenticated user"
        description: "Must be authenticated"
        operationId: "getDialogues"
        produces:
        - "application/json"
        parameters:
        - name: "amount"
          in: "query"
          description: "amount of dialogues to receive"
          required: false
          type: "integer"
        - name: "since"
          in: "query"
          description: "end list with that id, not including it"
          required: false
          type: "integer"
        - name: "find"
          in: "query"
          description: "filter for email addresses to return"
          required: false
          type: "string"
        - name: "folder"
          in: "query"
          description: "Folder id to return dialogues from"
          required: false
          type: "integer"
        responses:
          "200":
            description: "Returns list of dialogues"
          "400":
            description: "Invalid data provided"
          "401":
            description: "Not authenticated"
  /email/emails:
      get:
        tags:
        - "email"
        summary: "Returns emails of the selected dialogue"
        description: "Must be authenticated"
        operationId: "getEmails"
        produces:
        - "application/json"
        parameters:
        - name: "with"
          in: "query"
          description: "2nd user"
          required: true
          type: "string"
        - name: "amount"
          in: "query"
          description: "amount of emails to receive"
          required: false
          type: "integer"
        - name: "since"
          in: "query"
          description: "end list with that id, not including it"
          required: false
          type: "integer"
        responses:
          "200":
            description: "Returns list of emails"
          "400":
            description: "Invalid data provided"
          "401":
            description: "Not authenticated"
      delete:
        tags:
        - "email"
        summary: "Deletes list of emails"
        operationId: "deleteEmails"
        parameters:
        - in: "body"
          name: "body"
          description: "Emails ids to remove"
          required: true
          schema:
            $ref: "#/definitions/deleteEmails"
        responses:
          "200":
            description: "Emails were deleted"
          "400":
            description: "Invalid data provided"
          "401":
            description: "Not authenticated"
  /email:
    post:
      tags:
      - "email"
      summary: "Sends email"
      description: "Must be authenticated"
      operationId: "sendEmail"
      parameters:
      - in: "body"
        name: "body"
        description: "email to send"
        required: true
        schema:
          $ref: "#/definitions/email"
      responses:
        "200":
          description: "Email was sent"
        "400":
          description: "Invalid data provided"
        "401":
          description: "Not authenticated"
  /email/folders:
    get:
      tags:
      - "email"
      summary: "Returns list of folders"
      description: "Must be authenticated"
      operationId: "getFolders"
      responses:
        "200":
          description: "List of emails returned"
        "401":
          description: "Not authenticated"
  /email/folder:
    post:
      tags:
      - "email"
      summary: "Creates email folder"
      description: "Must be authenticated"
      operationId: "createFolder"
      parameters:
      - in: "body"
        name: "body"
        description: "new folder data"
        required: true
        schema:
          $ref: "#/definitions/newFolder"
      responses:
        "201":
          description: "Folder created successfully"
        "400":
          description: "Invalid data provided"
        "404":
          description: "Folder already exists"
        "401":
          description: "Not authenticated"
    put:
      tags:
      - "email"
      summary: "Puts dialogue to folder"
      description: "Must be authenticated"
      operationId: "addToFolder"
      parameters:
      - in: "body"
        name: "body"
        description: "what to put in folder"
        required: true
        schema:
          $ref: "#/definitions/putToFolder"
      responses:
        "200":
          description: "Dialogue was added to folder"
        "400":
          description: "Invalid data provided"
        "401":
          description: "Not authenticated"
    delete:
      tags:
      - "email"
      summary: "Removes folder, moves all emails to 0 folder"
      description: "Must be authenticated"
      operationId: "deleteFolder"
      parameters:
      - in: "body"
        name: "body"
        description: "folder id to delete"
        required: true
        schema:
          $ref: "#/definitions/deleteFolder"
      responses:
        "200":
          description: "Folder was deleted"
        "400":
          description: "Invalid data provided"
        "401":
          description: "Not authenticated"

definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      username:
        type: "string"
        example: "Wolf"
      fullname:
        type: "string"
        example: "Leo Volkov"
      avatarUrl:
        type: "string"
        example: "/media/avatars/wolf.jpg"
      reserveEmail:
        type: "string"
        example: "wolf@liokor.ru"
      joinedDate:
        type: "string"
        example: ""
      password:
        type: "string"
        example: "qwerty123"
      isAdmin:
        type: "boolean"
        example: false
  authData:
    type: "object"
    required:
    - "username"
    - "password"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  passwordChange:
    type: "object"
    required:
    - "oldPassword"
    - "newPassword"
    properties:
      oldPassword:
        type: "string"
      newPassword:
        type: "string"
  avatarChange:
    type: "object"
    required:
    - "avatarUrl"
    properties:
      avatarUrl:
        type: "string"
        example: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/4QBmRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEyAAIAAAAUAAAASlEQAAEAAAABAQAAAFERAAQAAAABAAALE1ESAAQAAAABAAALEwAAAAAyMDE2OjEyOjI4IDAwOjI1OjQ0AP/bAEMAAgEBAgEBAgICAgICAgIDBQMDAwMDBgQEAwUHBgcHBwYHBwgJCwkICAoIBwcKDQoKCwwMDAwHCQ4PDQwOCwwMDP/bAEMBAgICAwMDBgMDBgwIBwgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIACAAIAMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AP3J8beNb+fxBH4b8ORwSa1LEJrm5nUtb6VCTgSOB96RuQkYIzgk4Uc/OH7Xv7Ufwv8A2R/j18D/AAT8RPE02qa/8XvEcmludTlndLW2NrMqT+XCPJt431F9Pt1LAf8AHw7Z2RSulb9vL4weJvgD/wAE3fHfxi8LLNP4k0fXtL8YXMKXzWZ1DTrLXbKS4sGnVHZIZdPgmgPysAkzgqQTn8w/21/APjj/AIL9fGj4A/HP4M+GdXTStUih+H3i2yM4mHw41WyvXvZprmbChrd7W/SeOZFy6RIrJHO6QH5nAYKlmVJY7GrnU9YxesYxesfd2cmrNtpu7aTSR62IxE8JN4bDvlcdJNbtrfXe19Elo1q9T9U/gn+0V8M/jd+2f8W/hD4F8TR6L4o+E9rp7zrpmoSM08r+b9q/dSEwzx28htopVQMYpX2OVZlFfQPgnxpfw6/J4b8SRwR63FEZ7W5gUrb6tADgyID92RcgPGScZyMqePwr+G0Pjb/gjn/wVO/aa/aI+KngvxRB4Rs9Q1+z0CVYxaweP9Q13VVvtOtLWdz5ciG2imu7l4vN+yi0ZXQy7I2/TH/gnv8AHTxH+0t/wTZ8G/GjxLFdWfiDVPFOueKLS2nvmvJNO0648R3/AJFiLhlQyQx2MkcKnYgMcUYCKAADHYKlltJ47BLkUFeUVpGUVrL3dlJK7TSTukm2mPDYieLmsNiHzOWkW9Wm9td7X0aelndan0D4C8F6N8Rvg/4p+GvijT7fVNNjF94f1jTrlcx39jciT5WXr5csEpX3Ga/n0/a4/bH+E/7EP7Pnjr9m/wDZH8XfFK/svE/jJ9S8YeOdQ1KOFbu1ghWBdK02W3WKWS3MkY8y4ZUMqRsoe5huMx/0U+PPAeoDX4fEvhmaC3163i8ieCfi31SAHPlyY+669VcfQ8fd/J7wZ/wbX/AHwz8fdY1jx14i+JGmeCZJmm0vwUbI20dkWyWhbVId73FtHkrGUEEgCJvkkIYtngcwpZXSWAx79nGnpCctISgvh97ZSSspJtNtXSaZWIws8bN4nDLmctZRWslJ76btN6prRJ2dmfIv7F/7XHwu/b2/Zl8J/su/tY/EP4oaPBovjy11rwP4xs7tLoRrLA9kuk3s08U7xQhrqYxzuCkSzIpkgitwJP338W/DzQfhL8EvCPwt8I6bDpOkKtj4e0XToCWWxsbbZkDcSzJHBFgkknkEkk8/l9rH/Btr8Ebr9pXw/wCIvAfi74ia14HsbmK8v/BTaX9oN5JG+9YRq0hi+z2j7UV98c0uDJtlQspT9ZfAfgTUDr0viXxNNDca9cReRBBBn7PpcBOfLjz9526s569Bx94x2YUs0pPA4B+0U9JzjrCMH8XvbOTV1FJtpu7skLD4aeCmsTiVyuOsYvSTkttN0k9W3ZNKyuz/2Q=="
  imageUpload:
    type: "object"
    required:
    - "dataUrl"
    properties:
      dataUrl:
        type: "string"
        example: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/4QBmRXhpZgAATU0AKgAAAAgABQESAAMAAAABAAEAAAEyAAIAAAAUAAAASlEQAAEAAAABAQAAAFERAAQAAAABAAALE1ESAAQAAAABAAALEwAAAAAyMDE2OjEyOjI4IDAwOjI1OjQ0AP/bAEMAAgEBAgEBAgICAgICAgIDBQMDAwMDBgQEAwUHBgcHBwYHBwgJCwkICAoIBwcKDQoKCwwMDAwHCQ4PDQwOCwwMDP/bAEMBAgICAwMDBgMDBgwIBwgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIACAAIAMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/AP3J8beNb+fxBH4b8ORwSa1LEJrm5nUtb6VCTgSOB96RuQkYIzgk4Uc/OH7Xv7Ufwv8A2R/j18D/AAT8RPE02qa/8XvEcmludTlndLW2NrMqT+XCPJt431F9Pt1LAf8AHw7Z2RSulb9vL4weJvgD/wAE3fHfxi8LLNP4k0fXtL8YXMKXzWZ1DTrLXbKS4sGnVHZIZdPgmgPysAkzgqQTn8w/21/APjj/AIL9fGj4A/HP4M+GdXTStUih+H3i2yM4mHw41WyvXvZprmbChrd7W/SeOZFy6RIrJHO6QH5nAYKlmVJY7GrnU9YxesYxesfd2cmrNtpu7aTSR62IxE8JN4bDvlcdJNbtrfXe19Elo1q9T9U/gn+0V8M/jd+2f8W/hD4F8TR6L4o+E9rp7zrpmoSM08r+b9q/dSEwzx28htopVQMYpX2OVZlFfQPgnxpfw6/J4b8SRwR63FEZ7W5gUrb6tADgyID92RcgPGScZyMqePwr+G0Pjb/gjn/wVO/aa/aI+KngvxRB4Rs9Q1+z0CVYxaweP9Q13VVvtOtLWdz5ciG2imu7l4vN+yi0ZXQy7I2/TH/gnv8AHTxH+0t/wTZ8G/GjxLFdWfiDVPFOueKLS2nvmvJNO0648R3/AJFiLhlQyQx2MkcKnYgMcUYCKAADHYKlltJ47BLkUFeUVpGUVrL3dlJK7TSTukm2mPDYieLmsNiHzOWkW9Wm9td7X0aelndan0D4C8F6N8Rvg/4p+GvijT7fVNNjF94f1jTrlcx39jciT5WXr5csEpX3Ga/n0/a4/bH+E/7EP7Pnjr9m/wDZH8XfFK/svE/jJ9S8YeOdQ1KOFbu1ghWBdK02W3WKWS3MkY8y4ZUMqRsoe5huMx/0U+PPAeoDX4fEvhmaC3163i8ieCfi31SAHPlyY+669VcfQ8fd/J7wZ/wbX/AHwz8fdY1jx14i+JGmeCZJmm0vwUbI20dkWyWhbVId73FtHkrGUEEgCJvkkIYtngcwpZXSWAx79nGnpCctISgvh97ZSSspJtNtXSaZWIws8bN4nDLmctZRWslJ76btN6prRJ2dmfIv7F/7XHwu/b2/Zl8J/su/tY/EP4oaPBovjy11rwP4xs7tLoRrLA9kuk3s08U7xQhrqYxzuCkSzIpkgitwJP338W/DzQfhL8EvCPwt8I6bDpOkKtj4e0XToCWWxsbbZkDcSzJHBFgkknkEkk8/l9rH/Btr8Ebr9pXw/wCIvAfi74ia14HsbmK8v/BTaX9oN5JG+9YRq0hi+z2j7UV98c0uDJtlQspT9ZfAfgTUDr0viXxNNDca9cReRBBBn7PpcBOfLjz9526s569Bx94x2YUs0pPA4B+0U9JzjrCMH8XvbOTV1FJtpu7skLD4aeCmsTiVyuOsYvSTkttN0k9W3ZNKyuz/2Q=="
  email:
    type: "object"
    required:
    - "recipient"
    - "subject"
    - "body"
    properties:
      recipient:
        type: "string"
      subject:
        type: "string"
      body:
        type: "string"
  createDialogue:
    type: "object"
    required:
    - "name"
    properties:
      username:
        type: "string"
        example: "korolion@liokor.ru"
  deleteEmails:
    type: "object"
    required:
    - "ids"
    properties:
      ids:
        type: "array"
        items:
          type: integer
        example: [1, 2, 3]
  newFolder:
    type: "object"
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "important"
  putToFolder:
    type: "object"
    required:
    - "folderId"
    - "dialogueId"
    properties:
      folderId:
        type: "integer"
      dialogueId:
        type: "integer"
  deleteFolder:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "integer"
        example: 0
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
