// Code generated by MockGen. DO NOT EDIT.
// Source: liokor_mail/internal/pkg/mail (interfaces: MailUseCase)

// Package mocks is a generated GoMock package.
package mocks

import (
	mail "liokor_mail/internal/pkg/mail"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMailUseCase is a mock of MailUseCase interface.
type MockMailUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockMailUseCaseMockRecorder
}

// MockMailUseCaseMockRecorder is the mock recorder for MockMailUseCase.
type MockMailUseCaseMockRecorder struct {
	mock *MockMailUseCase
}

// NewMockMailUseCase creates a new mock instance.
func NewMockMailUseCase(ctrl *gomock.Controller) *MockMailUseCase {
	mock := &MockMailUseCase{ctrl: ctrl}
	mock.recorder = &MockMailUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailUseCase) EXPECT() *MockMailUseCaseMockRecorder {
	return m.recorder
}

// GetDialogues mocks base method.
func (m *MockMailUseCase) GetDialogues(arg0 string, arg1, arg2 int, arg3 string) ([]mail.Dialogue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialogues", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]mail.Dialogue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDialogues indicates an expected call of GetDialogues.
func (mr *MockMailUseCaseMockRecorder) GetDialogues(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialogues", reflect.TypeOf((*MockMailUseCase)(nil).GetDialogues), arg0, arg1, arg2, arg3)
}

// GetEmails mocks base method.
func (m *MockMailUseCase) GetEmails(arg0, arg1 string, arg2, arg3 int) ([]mail.DialogueEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmails", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]mail.DialogueEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmails indicates an expected call of GetEmails.
func (mr *MockMailUseCaseMockRecorder) GetEmails(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmails", reflect.TypeOf((*MockMailUseCase)(nil).GetEmails), arg0, arg1, arg2, arg3)
}

// SendEmail mocks base method.
func (m *MockMailUseCase) SendEmail(arg0 mail.Mail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockMailUseCaseMockRecorder) SendEmail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockMailUseCase)(nil).SendEmail), arg0)
}
