// Code generated by MockGen. DO NOT EDIT.
// Source: liokor_mail/internal/pkg/mail (interfaces: MailRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	mail "liokor_mail/internal/pkg/mail"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockMailRepository is a mock of MailRepository interface.
type MockMailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMailRepositoryMockRecorder
}

// MockMailRepositoryMockRecorder is the mock recorder for MockMailRepository.
type MockMailRepositoryMockRecorder struct {
	mock *MockMailRepository
}

// NewMockMailRepository creates a new mock instance.
func NewMockMailRepository(ctrl *gomock.Controller) *MockMailRepository {
	mock := &MockMailRepository{ctrl: ctrl}
	mock.recorder = &MockMailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailRepository) EXPECT() *MockMailRepositoryMockRecorder {
	return m.recorder
}

// AddMail mocks base method.
func (m *MockMailRepository) AddMail(arg0 mail.Mail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMail indicates an expected call of AddMail.
func (mr *MockMailRepositoryMockRecorder) AddMail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMail", reflect.TypeOf((*MockMailRepository)(nil).AddMail), arg0)
}

// CountMailsFromUser mocks base method.
func (m *MockMailRepository) CountMailsFromUser(arg0 string, arg1 time.Duration) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMailsFromUser", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMailsFromUser indicates an expected call of CountMailsFromUser.
func (mr *MockMailRepositoryMockRecorder) CountMailsFromUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMailsFromUser", reflect.TypeOf((*MockMailRepository)(nil).CountMailsFromUser), arg0, arg1)
}

// GetDialoguesForUser mocks base method.
func (m *MockMailRepository) GetDialoguesForUser(arg0 string, arg1, arg2 int, arg3, arg4 string) ([]mail.Dialogue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDialoguesForUser", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]mail.Dialogue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDialoguesForUser indicates an expected call of GetDialoguesForUser.
func (mr *MockMailRepositoryMockRecorder) GetDialoguesForUser(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDialoguesForUser", reflect.TypeOf((*MockMailRepository)(nil).GetDialoguesForUser), arg0, arg1, arg2, arg3, arg4)
}

// GetMailsForUser mocks base method.
func (m *MockMailRepository) GetMailsForUser(arg0, arg1 string, arg2, arg3 int) ([]mail.DialogueEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMailsForUser", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]mail.DialogueEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMailsForUser indicates an expected call of GetMailsForUser.
func (mr *MockMailRepositoryMockRecorder) GetMailsForUser(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMailsForUser", reflect.TypeOf((*MockMailRepository)(nil).GetMailsForUser), arg0, arg1, arg2, arg3)
}
