name: CI/CD
on: [push]
jobs:
  eslint_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'
      - name: Check go
        run: go version
      - name: Deploy (Conditional)
        uses: easingthemes/ssh-deploy@v2
        if: ${{ github.ref == 'refs/heads/korolion/dev' }}
        env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOYER_SSH_PRIVATE }}
            SOURCE: dist/
            REMOTE_HOST: 89.208.197.127
            REMOTE_USER: deployer
            TARGET: /home/deployer/go_backend/
